---
- hosts: west
  tasks: 
    - name: "Validating backend service from west namespace"
      command: "kubectl -n {{ namespace }} exec deploy/skupper-service-controller -- curl -s -v http://backend:8080/api/hello"
      register: out
      failed_when: out.failed or "HTTP/1.1 200 OK" not in out.stderr
    - name: "Validating frontend service from west namespace"
      command: "kubectl -n {{ namespace }} exec deploy/skupper-service-controller -- curl -s -v http://frontend:8080"
      register: out
      failed_when: out.failed or "HTTP/1.1 200 OK" not in out.stderr
