#!/usr/bin/python3

from common import *

def main():
    check_environment()

    call("minikube version")

    test_profile = "skupper-example-hello-world"
    test_kubeconfig = make_temp_file()
    west_kubeconfig = make_temp_file()
    east_kubeconfig = make_temp_file()

    with open("/tmp/minikube-tunnel-output", "w") as tunnel_output_file:
        try:
            with working_env(KUBECONFIG=test_kubeconfig):
                call(f"minikube start -p {test_profile}")

                copy(test_kubeconfig, east_kubeconfig)
                copy(test_kubeconfig, west_kubeconfig)

                with start_process(f"minikube tunnel -p {test_profile}", output=tunnel_output_file):
                    run_test(west_kubeconfig, east_kubeconfig)

                notice("Test result: PASSED")
        except:
            error("Test result: FAILED")
            raise
        finally:
            call(f"minikube tunnel -p {test_profile} --cleanup")
            call(f"minikube delete -p {test_profile}")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
