#!/usr/bin/python3

from common import *

def main():
    check_environment()

    west_kubeconfig = ARGS[1]
    east_kubeconfig = ARGS[2]

    try:
        run_test(west_kubeconfig, east_kubeconfig)
        notice("Test result: PASSED")
    except:
        error("Test result: FAILED")
        raise

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
