#!/usr/bin/python3

from common import *

def main():
    check_environment()

    call("minikube version")

    west_kubeconfig = make_temp_file()
    west_profile = "skupper-example-hello-world-west"
    east_kubeconfig = make_temp_file()
    east_profile = "skupper-example-hello-world-east"

    with open("/tmp/minikube-tunnel-output", "w") as tunnel_output_file:
        try:
            with working_env(KUBECONFIG=west_kubeconfig):
                call(f"minikube start -p {west_profile}")

            with working_env(KUBECONFIG=east_kubeconfig):
                call(f"minikube start -p {east_profile}")

            with working_env(KUBECONFIG=west_kubeconfig):
                with start_process(f"minikube tunnel -p {west_profile}", output=tunnel_output_file):
                    run_test(west_kubeconfig, east_kubeconfig)

            notice("Test result: PASSED")
        except:
            error("Test result: FAILED")
            raise
        finally:
            call(f"minikube tunnel -p {west_profile} --cleanup")
            call(f"minikube delete -p {west_profile}")
            call(f"minikube delete -p {east_profile}")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
