name: Build and Push Multi-Arch Image
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        run: |
          echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u "${{ secrets.QUAY_USER }}" --password-stdin

      - name: Build and Push Multi-Arch Image
        run: |
          cd frontend && \
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/s390x \
            -t quay.io/skupper/hello-world-frontend \
            --push -f Containerfile .
